### ISSUE TITLE
Add --ignore-plugins flag to abell serve

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#77]
**Is your feature request related to a problem? Please describe.**

Plugins can have additional sources (CHANGELOGS, READMES) which can slow down the development process if you don't want to test them on every run.

**Describe the solution you'd like**

Calling `abell serve --ignore-plugins` should ignore the plugin execution.

**Approach**

1. We will have to register this flag in [bin/abell.js](https://github.com/abelljs/abell/blob/main/bin/abell.js#L22)
2. Add flag value `true` or `false` to `programInfo` in [src/commands/serve.js](https://github.com/abelljs/abell/blob/main/src/commands/serve.js#L245)
3. On true, ignore calling `executeAfterBuildPlugins` and `executeBeforeBuildPlugins` functions in the serve.js
4. ignore calling `executeBeforeHTMLWritePlugins` from [src/utils/generate-site.js](https://github.com/abelljs/abell/blob/312dd6a057ce0d39142b803ad220798706137e9e/src/utils/generate-site.js#L154)

This issue can be a good start for beginners so if you're experienced and comfortable with GitHub, Please look for other issues and leave this issue for beginners to that they can get started :D

**Comment by abhijit-hota** [comment]
Hey, I'm working on this. (I guess I'm done too). 

Just a query: What exactly does the [`createContent`](https://github.com/abelljs/abell/blob/main/src/commands/serve.js#L236) function do and **can I move the `programInfo` property assignments before that function**?

Something like this:

```js
async function serve(command) {
  const programInfo = getProgramInfo();
  
  programInfo.ignorePlugins = command['ignore-plugins'];
  programInfo.port = command.port;
  programInfo.logs = 'minimum';
  programInfo.task = 'serve';
  programInfo.abellConfig.outputPath = '.debug';

  // createContent function that goes to plugins
  const createContent = (pluginNode) => {
    programInfo.contentMap[pluginNode.slug] = getSourceNodeFromPluginNode(
      pluginNode
    );
  };
  .
  .
  .
}
```

Also, (guessing this because it involves plugins and I couldn't really find any use of it in serving other than the `*BuildPlugins` functions) should we ignore executing that function too while serving?

**Comment by saurabhdaware** [comment]
`createContent` function is used in plugins to create source plugins 

https://github.com/abelljs/official-plugins/blob/main/abell-source-devto/plugin/index.js#L23

Is there any specific reason to move it below? I don't think so it breaks anything as long as it is above the executeBuildPlugins function but it is just safe to change minimal things possible 😅

**Comment by saurabhdaware** [comment]
If we ignore `executeBeforeBuild` function then createContent won't be called anyway so it is fine to keep it out of the if condition for now

**Comment by pantharshit00** [comment]
We should have integration tests for official plugins. I will create an issue for it. Then someone can pick it up.

Having those tests would be valuable as we will have some confidence when we will change the renderer code.

**Comment by saurabhdaware** [comment]
We have https://github.com/abelljs/abell/blob/main/examples/with-plugin/with-plugin.spec.js to test `beforeHTMLWrite` and `beforeBuild` with `createContent()`. I just realized It lacks the test for `afterBuild` though.

**Comment by pantharshit00** [comment]
@saurabhdaware That is a unit test though. 

Integration test is also required here between plugin as unit tests can't catch bugs caused by order of execution

**Comment by abhijit-hota** [comment]
@saurabhdaware 

> Is there any specific reason to move it below?

Currently the `executeBeforeBuildPlugins` is executed before all the properties of `programInfo` are assigned. In order to check for the `--ignore-plugin` flag, I had to assign a property before the execution. So I thought why not assign them at one place?(and the beginning of the function seemed like a really good place)

> I don't think so it breaks anything as long as it is above the executeBuildPlugins function but it is just safe to change minimal things possible 😅

Totally agree with this and that's the reason I thought asking for opinions would be better (even if it is such a small thing) as I'm new to the repository.

> If we ignore executeBeforeBuild function then createContent won't be called anyway so it is fine to keep it out of the if condition for now

Yeah, got it! 👍
