### ISSUE TITLE
integrate babel

### ISSUE THREAD

**Issue by judicaelandria** [abelljs/abell#98]
**Is your feature request related to a problem? Please describe.**
here in Abell, we use required to import a file, we can't use the import like the feature from babel

**Describe the solution you'd like**
So I think using import is better that require, it's the same thing but someone maybe like using import instead of required (like me) and someone likes to use require, it would be cool if we Abell support these two

**Comment by judicaelandria** [comment]
I saw in the docs that everything inside double brackets is executed on the build, but isn't there another solution for it?

**Comment by saurabhdaware** [comment]
The require syntax is kind of intended to remind people that things inside curly braces are Node.js and not frontend javascript. 

However, Babel would definitely help in other things like it can allow us write latest ES syntax and if import works in that case, then it will be fine since user would intentionally install babel and they would know that import is syntax sugar.

I will definitely be exploring ways to plug webpack and babel. Thanks for opening the issue! Lets keep this open

**Comment by saurabhdaware** [comment]
This is fixed in https://github.com/abelljs/abell/releases/tag/abell-v1.0.0-alpha.47. Thanks for opening the issue @judicaelandria 👯
